### ISSUE TITLE
Inbound liquidity section addition: the ease and immediacy of getting inbound liquidity by using sites like Bitrefill, et al.

### ISSUE THREAD

**Issue by argentoblitz** [openoms/lightning-node-management#10]
In the inbound liquidity section, would be lovely to see a section (in my opinion, should be high up, due to it's non-technical simplicity and directness) that covers strategically-oversized-outbound-channel-opening balanced by personal ordinary spending. Sample text could be:

If you already pay online for purchases (app store/smartphone app and subscription purchases, PS/Xbox/Switch game console downloads, Amazon purchases, cell phone payments, etc.)

1. Open an outbound Lightning channel, *double the size* you wish it to ultimately be, to a node you like from 1ml.com / etc. that is well-ranked for uptime, etc. 

 2. Use Bitrefill or similar sites to pay routine and personal expenses, ultimately using half of the funds from this channel. 

Now you have a balanced channel simply by spending what you would have anyways. For example, you can buy Apple App Store or Google Play store cards for subscriptions you would have paid for anyways monthly, and they will just successively deduct what you leave on there. So if you wish to have $XXX in inbound capacity, and know you will spend that this year, you can buy gift card codes on Bitrefill in advance if you wish to speed up your inbound capacity. Or do it as-you-go and it grows gradually.

**Comment by openoms** [comment]
Thank you for the suggestion. This is more relevant then ever. Added a link for Bitrefill in https://github.com/openoms/lightning-node-management/commit/202b4133a44b2749185391a67a9b548fad19d781
