### ISSUE TITLE
balanceofsatoshis usage example

### ISSUE THREAD

**Issue by isuldor** [openoms/lightning-node-management#8]
Okay, I think I've now wasted enough cycles misusing `bos rebalance` that I've narrowed down how you're actually supposed to use it.  First off, it will only try to rebalance in small amounts, so unless you want to spend eons of time running it manually you should specify capacity targets. It will then keep trying to route circular payments until the channel hits your target. You can only set either an inbound target capacity or an outbound one. 

```bash
if [[ ${OUTBOUND_CAPACITY} < ${INBOUND_CAPACITY} ]];then
    LIMIT_REBALANCE="--in-target-outbound $(expr ${INBOUND_CAPACITY} / 2)"
else
    LIMIT_REBALANCE="--out-target-inbound $(expr ${OUTBOUND_CAPACITY} / 2)"
fi
   
bos rebalance --out ${OUTBOUND_PUBKEY} --in ${INBOUND_PUBKEY} --max-fee-rate ${INBOUND_FEERATE} ${LIMIT_REBALANCE}
```

INBOUND_CAPACITY being the capacity of your `--in` channel.
OUTBOUND_CAPACITY being the capacity of your `--out` channel.

I know this is not at all concise enough of an explanation to go into the markdown article, but perhaps you can paraphrase.

Anyway, thanks for all your efforts @openoms. I haven't actually been using the raspi-stuff, but stumbled across various git issues you've opened in other repos that I found to be informative.

**Comment by openoms** [comment]
I am actually running `bos rebalance` as a cronjob (example):
```
17 * * * * /home/bos/.npm-global/bin/bos rebalance --avoid 021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d --in bfx-lnd1
47 * * * * /home/bos/.npm-global/bin/bos rebalance --avoid 021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d --in bfx-lnd0
```

**Comment by isuldor** [comment]
Hrm, I'm probably overthinking it then. I've been trying to compensate for a very high failure rate on rebalances, but that's probably due to my peer selection.  I'll have to keep thinking about how to best operate a routing node, because I seem to be far away from figuring it out so far!
